### ISSUE TITLE
When my applications starts i get this error

### ISSUE THREAD

**Issue by DrStanley** [ceryle/SegmentedButton#46]
Fatal Exception: java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed
       at android.graphics.Canvas.checkValidClipOp(Canvas.java:789)
       at android.graphics.Canvas.clipPath(Canvas.java:1017)
       at co.ceryle.segmentedbutton.RoundedCornerLayout.dispatchDraw(RoundedCornerLayout.java:82)
       at android.view.View.buildDrawingCacheImpl(View.java:20078)
       at android.view.View.buildDrawingCache(View.java:19940)
       at android.view.View.draw(View.java:20543)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4425)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4204)
       at android.view.View.updateDisplayListIfDirty(View.java:19669)
       at android.view.View.draw(View.java:20551)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4425)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4204)
       at co.ceryle.segmentedbutton.SegmentedButtonGroup.dispatchDraw(SegmentedButtonGroup.java:163)
       at android.view.View.updateDisplayListIfDirty(View.java:19669)
       at android.view.View.draw(View.java:20551)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4425)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4204)
       at android.view.View.updateDisplayListIfDirty(View.java:19669)
       at android.view.View.draw(View.java:20551)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4425)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4204)
       at android.view.View.draw(View.java:20846)
       at android.view.View.updateDisplayListIfDirty(View.java:19678)
       at android.view.View.draw(View.java:20551)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4425)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4204)
       at android.view.View.updateDisplayListIfDirty(View.java:19669)
       at android.view.View.draw(View.java:20551)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4425)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4204)
       at android.view.View.draw(View.java:20846)
       at android.widget.ScrollView.draw(ScrollView.java:1739)
       at android.view.View.updateDisplayListIfDirty(View.java:19678)
       at android.view.View.draw(View.java:20551)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4425)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4204)
       at android.view.View.updateDisplayListIfDirty(View.java:19669)
       at android.view.View.draw(View.java:20551)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4425)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4204)
       at android.view.View.updateDisplayListIfDirty(View.java:19669)
       at android.view.View.draw(View.java:20551)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4425)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4204)
       at android.view.View.updateDisplayListIfDirty(View.java:19669)
       at android.view.View.draw(View.java:20551)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4425)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4204)
       at android.view.View.updateDisplayListIfDirty(View.java:19669)
       at android.view.View.draw(View.java:20551)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4425)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4204)
       at android.view.View.updateDisplayListIfDirty(View.java:19669)
       at android.view.View.draw(View.java:20551)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4425)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4204)
       at android.view.View.draw(View.java:20846)
       at com.android.internal.policy.DecorView.draw(DecorView.java:785)
       at android.view.View.updateDisplayListIfDirty(View.java:19678)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3490)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3290)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2644)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1554)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7507)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:977)
       at android.view.Choreographer.doCallbacks(Choreographer.java:785)
       at android.view.Choreographer.doFrame(Choreographer.java:717)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:963)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6819)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:912)

**Comment by DrStanley** [comment]
app.build
    implementation 'com.github.ceryle:SegmentedButton:v1.0'

**Comment by AhmadAyyaz1993** [comment]
I am getting the same issue !!
